const assert=require('node:assert/strict');
const {loadEngine,makeSession}=require('./harness');
const LX=loadEngine();let checks=0;
function check(value,message){assert(value,message);checks++;}
(async()=>{
 const s=makeSession(LX);const run=async c=>{const result=await s.run(c);assert.equal(result.status,0,c+'\n'+result.out);return result.out;};
 const repo=()=>LX.Git.Repo.find(s.sh);
 await run('mkdir projeto && cd projeto');await run('git init');
 check((await s.run('git commit -m inicial')).status!==0,'identity is required');
 await run('git config user.name Aluno');await run('git config user.email aluno@example.invalid');
 await run('echo inicial > index.html');await run('git add index.html');await run('echo posterior > index.html');
 check((await run('git status --short')).includes('AM index.html'),'staged and working contents are distinct');
 await run('git commit -m inicial');check(repo().snapshot()['index.html']==='inicial\n','commit uses index snapshot');
 await run('echo novo > untracked.txt');check(!(await run('git diff')).includes('untracked.txt'),'diff excludes untracked files');
 check((await s.run('git switch -c feature')).status!==0,'switch protects changes');
 await run('git restore index.html');await run('git switch -c feature');await run('echo feature > feature.txt');await run('git add feature.txt');await run('git commit -m feature');const feature=repo().head;
 await run('git switch main');await run('git merge feature');check(repo().head===feature,'fast-forward preserves commit');
 await run('git switch -c conflito');await run('echo lado-A > index.html');await run('git add index.html');await run('git commit -m lado-A');
 await run('git switch main');await run('echo lado-B > index.html');await run('git add index.html');await run('git commit -m lado-B');const before=repo().head;
 check((await s.run('git merge conflito')).status===1,'divergent content conflicts');
 check(repo().working()['index.html'].includes('<<<<<<< HEAD'),'conflict has markers');
 check((await s.run('git commit -m incorreto')).status!==0,'unresolved conflicts cannot commit');
 await run('git merge --abort');check(repo().head===before&&repo().working()['index.html']==='lado-B\n','abort restores initial state');
 await s.run('git merge conflito');await run('echo combinado > index.html');await run('git add index.html');await run('git commit -m resolvido');
 check(repo().d.commits[repo().head].parents.length===2,'merge commit has two parents');
 const merge=repo().head;await run('git reset --soft HEAD~1');check(repo().d.index['index.html']==='combinado\n','soft preserves index');
 await run('git reset --mixed HEAD');check(repo().d.index['index.html']==='lado-B\n'&&repo().working()['index.html']==='combinado\n','mixed resets only index');
 await run('git reset --hard HEAD');check(repo().working()['index.html']==='lado-B\n','hard resets tracked working files');
 check(repo().d.commits[merge]!==undefined,'reset retains commit for recovery');await run('git branch recuperado '+merge);
 await run('echo rascunho > index.html');await run('git stash');check(repo().working()['index.html']==='lado-B\n','stash cleans working tree');
 await run('git stash apply');check(repo().d.stash.length===1&&repo().working()['index.html']==='rascunho\n','apply retains stash');
 await run('git restore index.html');await run('git stash pop');check(repo().d.stash.length===0,'pop removes successfully applied entry');await run('git restore index.html');
 await run('gh repo create aluno/teste --private');await run('git remote add origin https://github.com/aluno/teste.git');
 check((await s.run('git push -u origin main')).status!==0,'push requires simulated authentication');
 await run('gh auth login');await run('git push -u origin main');check(repo().d.upstream.main==='origin/main','push -u records tracking');
 const remote=LX.Github.get(s.m,'aluno/teste');remote.protected=true;check((await s.run('git push origin main')).status!==0,'protected branch blocks direct push');remote.protected=false;
 await run('cd ..');await run('git clone https://github.com/aluno/teste.git copia');await run('cd copia');check(repo().head===before&&repo().root.endsWith('/copia'),'clone recreates history and files');
 const x=makeSession(LX);await x.run('git init');await x.run('git config user.name Aluno');await x.run('git config user.email aluno@example.invalid');await x.run('echo root > root.txt');await x.run('git add .');await x.run('git commit -m root');const first=LX.Git.Repo.find(x.sh).head;
 check((await x.run('git show')).out.includes('+root'),'root commit diff uses empty parent');await x.run('git revert '+first);check(!('root.txt'in LX.Git.Repo.find(x.sh).snapshot()),'revert root removes its addition');
 console.log(`Git: ${checks} semantic checks passed.`);
})().catch(e=>{console.error(e);process.exitCode=1;});
