/* GitHub local: nenhum pedido de rede, token ou credencial real. */
'use strict';
(function(){
 const G=LX.Git;
 const hub=m=>(m.gitHub||= {repos:{},auth:null});
 const name=url=>String(url||'').replace(/^https:\/\/github\.com\//,'').replace(/^git@github\.com:/,'').replace(/\.git$/,'');
 const get=(m,url)=>hub(m).repos[name(url)];
 function create(m,n,visibility='private'){n=name(n);if(!/^[\w.-]+\/[\w.-]+$/.test(n))G.fail('Use owner/repository');if(get(m,n))G.fail('Repository already exists');return hub(m).repos[n]={name:n,visibility,description:'',defaultBranch:'main',commits:{},branches:{main:null},tags:{},issues:[],prs:[],releases:[],runs:[],protected:false};}
 function remoteFor(r){const x=get(r.sh.m,r.d.remotes.origin);if(!x)G.fail('Configure origin with a repository created in the laboratory');return x;}
 function runCI(remote,branch){const id=remote.branches[branch],tree=remote.commits[id]?.tree||{};for(const[p,text]of Object.entries(tree)){if(!/^\.github\/workflows\/.*\.ya?ml$/.test(p))continue;let status='failure',reason='Workflow precisa de on, jobs e steps.';try{const y=LX.lerYaml(text);if(y.on&&y.jobs){const steps=Object.values(y.jobs).flatMap(j=>j.steps||[]);const checks=steps.filter(s=>s.run);const allowed=['test -f README.md','test -f index.html'];if(checks.length&&checks.every(s=>allowed.includes(s.run))){status=checks.every(s=>s.run.endsWith('README.md')?'README.md'in tree:'index.html'in tree)?'success':'failure';reason=status==='success'?'Arquivos necessários presentes.':'Arquivo necessário ausente.';}else reason='Laboratório executa apenas test -f README.md e test -f index.html. Outros workflows podem ser estudados como texto.';}}catch(e){reason=e.message;}remote.runs.push({path:p,commit:id,status,reason});}}
 function transfer(r,cmd,a,out){const params=a.filter(x=>!x.startsWith('-')),n=params[0]||'origin',b=params[1]||r.d.branch,remote=get(r.sh.m,r.d.remotes[n]);if(!remote)G.fail('fatal: remote repository not found in the laboratory');if(!hub(r.sh.m).auth)G.fail('Authentication required in the laboratory: gh auth login');
  if(cmd==='push'){if(a.includes('--tags')){remote.tags=G.copy(r.d.tags);Object.assign(remote.commits,G.copy(r.d.commits));out('Tags pushed (laboratório)');return 0;}const old=remote.branches[b];if(remote.protected&&b===remote.defaultBranch)G.fail('Protected branch: use a reviewed Pull Request');if(old&&!r.ancestors(r.d.branches[b]).includes(old))G.fail('! [rejected] non-fast-forward; fetch and integrate remote changes');if(!r.d.branches[b])G.fail('error: src refspec does not match any');Object.assign(remote.commits,G.copy(r.d.commits));remote.branches[b]=r.d.branches[b];r.d.tracking[n+'/'+b]=remote.branches[b];if(a.includes('-u')||a.includes('--set-upstream'))r.d.upstream[b]=n+'/'+b;r.save();runCI(remote,b);out(b+' -> '+b+' (laboratório local)');return 0;}
  Object.assign(r.d.commits,G.copy(remote.commits));for(const[k,id]of Object.entries(remote.branches))r.d.tracking[n+'/'+k]=id;r.save();out('Fetched '+n);if(cmd==='pull'){if(a.includes('--ff-only')&&r.head&&!r.ancestors(r.d.tracking[n+'/'+b]).includes(r.head)&&!r.ancestors(r.head).includes(r.d.tracking[n+'/'+b]))G.fail('fatal: Not possible to fast-forward, aborting.');out(r.merge(n+'/'+b));return r.d.conflicts.length?1:0;}return 0;
 }
 function action(r,group,op,opts={}){
  const m=r.sh.m,remote=remoteFor(r);
  if(group==='issue'&&op==='create'){if(!opts.title?.trim())G.fail('Title required');const issue={number:remote.issues.length+1,title:opts.title,body:opts.body||'',label:opts.label||'',assignee:opts.assignee||'',milestone:opts.milestone||'',state:'open'};remote.issues.push(issue);return issue;}
  if(group==='pr'&&op==='create'){const source=opts.source?get(m,opts.source):remote;const head=opts.head||r.d.branch,base=opts.base||'main';if(!source?.branches[head]||!remote.branches[base]||source.branches[head]===remote.branches[base])G.fail('Push a branch with new commits before opening a PR');const pr={number:remote.prs.length+1,title:opts.title||'Proposta de alteração',body:opts.body||'',head,base,source:source.name,state:'open',review:'pending',comments:[]};remote.prs.push(pr);return pr;}
  const pr=remote.prs.find(p=>p.number===+(opts.number||1));
  if(group==='pr'&&['review','comment','close','merge'].includes(op)){if(!pr||pr.state!=='open')G.fail('Open PR not found');if(op==='review'){pr.review=opts.requestChanges?'changes_requested':'approved';pr.reviewedHead=get(m,pr.source).branches[pr.head];}if(op==='comment'){if(!opts.body?.trim())G.fail('Comment required');pr.comments.push(opts.body);}if(op==='close')pr.state='closed';if(op==='merge'){if(pr.review!=='approved'||pr.reviewedHead!==get(m,pr.source).branches[pr.head])G.fail('A revisão simulada precisa aprovar o PR');const source=get(m,pr.source);Object.assign(remote.commits,G.copy(source.commits));const temp=new G.Repo(r.sh,r.root,G.copy(r.d));Object.assign(temp.d,{commits:G.copy(remote.commits),branches:G.copy(remote.branches),branch:pr.base,index:G.copy(remote.commits[remote.branches[pr.base]]?.tree||{})});const base=temp.ancestors(remote.branches[pr.base]).find(x=>temp.ancestors(source.branches[pr.head]).includes(x));const result=temp.mergeTrees(temp.snapshot(base),temp.snapshot(remote.branches[pr.base]),temp.snapshot(source.branches[pr.head]),pr.head);if(result.conflicts.length)G.fail('PR has conflicts; resolve locally and push');const id='ff'+Number(remote.prs.length).toString(16).padStart(6,'0')+source.branches[pr.head].slice(8);remote.commits[id]={id,tree:result.tree,parents:[remote.branches[pr.base],source.branches[pr.head]],message:pr.title,author:'Revisão do laboratório',email:'review@example.invalid'};pr.baseCommit=remote.branches[pr.base];pr.headCommit=source.branches[pr.head];remote.branches[pr.base]=id;pr.state='merged';runCI(remote,pr.base);}return pr;}
  if(group==='release'&&op==='create'){const tag=opts.tag;if(!remote.tags[tag])G.fail('Push the tag before creating a release');if(remote.releases.some(x=>x.tag===tag))G.fail('Release already exists');const release={tag,title:opts.title||tag,notes:opts.notes||''};remote.releases.push(release);return release;}
  G.fail('Unsupported GitHub laboratory action');
 }
 LX.Github={hub,get,create,name,transfer,action,remoteFor,runCI};
 LX.defcmd({name:'gh',help:'GitHub CLI educacional: auth login/status, repo create/view/fork, issue create/list, pr create/list/review/comment/merge/close, release create/list, run list.',run:async({sh,io,args})=>{try{const a=args.slice(),group=a.shift(),op=a.shift();const val=k=>a.includes(k)?a[a.indexOf(k)+1]:undefined;let result;
  if(group==='auth'){if(op==='login')hub(sh.m).auth={user:'aluno',protocol:val('--git-protocol')||'https'};else if(op!=='status')G.fail('Use gh auth login or status');result=hub(sh.m).auth?'Autenticado como aluno no laboratório local. Nenhuma credencial real utilizada.':'Não autenticado no laboratório.';}
  else if(group==='repo'&&op==='create'){result=create(sh.m,a[0],a.includes('--public')?'public':'private');result.description=val('--description')||'';}
  else if(group==='repo'&&op==='fork'){const source=get(sh.m,a[0]);if(!source)G.fail('Repository not found');result=create(sh.m,'aluno/'+source.name.split('/')[1],source.visibility);Object.assign(result,{commits:G.copy(source.commits),branches:G.copy(source.branches),forkOf:source.name});}
  else {const r=G.Repo.find(sh);if(op==='list'||group==='repo'&&op==='view'){const remote=remoteFor(r);result=group==='issue'?remote.issues:group==='pr'?remote.prs:group==='release'?remote.releases:group==='run'?remote.runs:remote;}else result=action(r,group,op,{title:val('--title'),body:val('--body'),head:val('--head'),base:val('--base'),source:val('--source'),number:/^\d+$/.test(a[0])?+a[0]:1,tag:a[0],notes:val('--notes'),label:val('--label'),assignee:val('--assignee'),milestone:val('--milestone'),requestChanges:a.includes('--request-changes')});}
  io.stdout.write(typeof result==='string'?result+'\n':JSON.stringify(result,null,2)+'\n');return 0;
 }catch(e){io.stderr.write(e.message+'\n');return 1;}}});
})();
